backend:
  name: git-gateway
  branch: main
media_folder: "public/images/"
public_folder: "/images/"
site_url: https://outdoor-inspiration.netlify.app
display_url: https://outdoor-inspiration.netlify.app
slug:
  encoding: "ascii"
  clean_accents: true
collections:
  - name: "national-parks"
    label: "National Parks"
    label_singular: "National Park"
    folder: "src/parks"
    format: 'json'
    create: true
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Location", name: "location", widget: "string", required: true}
      - label: "Date Established"
        name: "date"
        widget: "date"
        required: true
        format: 'MMM Do, YYYY'
      - {label: "Description", name: "description", widget: "text", required: true}
      - label: "NPS Website URL"
        name: "nps-url"
        widget: "string"
        required: true
        pattern: ['(http(s)?:\/\/.)?(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)', "Must be a valid URL"]
      - {label: "Flickr Gallery ID", name: "gallery-id", widget: "string", required: true}

